# Generated by Django 4.0.3 on 2022-03-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='debt',
        ),
    ]
