# Generated by Django 4.0.3 on 2022-03-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='debt',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='movies_rented',
            field=models.ManyToManyField(to='base_app.movie'),
        ),
    ]
