# Generated by Django 4.0.3 on 2022-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_remove_user_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentmovie',
            name='return_date',
        ),
        migrations.AddField(
            model_name='rentmovie',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
