# Generated by Django 4.0.3 on 2022-03-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_user_debt_user_movies_rented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='movies_rented',
            field=models.ManyToManyField(related_name='movies', to='base_app.movie'),
        ),
    ]
