# Generated by Django 4.0.3 on 2022-03-26 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_remove_rentmovie_return_date_rentmovie_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmovie',
            name='rent_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='rentmovie',
            name='updated_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
