# Generated by Django 4.0.3 on 2022-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_alter_rentmovie_rent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=8.0),
            preserve_default=False,
        ),
    ]
