# Generated by Django 4.0.3 on 2022-03-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmovie',
            name='status',
            field=models.CharField(choices=[('rented currently', 'Current'), ('rented previously', 'Previous')], max_length=30),
        ),
    ]
